name: build

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20.4"
      - run: go test -v -race
      - uses: goreleaser/goreleaser-action@v4
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: "v1.18.2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
